# Build our app using chef with debian as its final image
name: build_debian_chef

# needs to read the code, and needs to be able to upload to your packages
permissions:
  contents: read
  packages: write

# we run the workflow when we git a new git tag
on:
  push:
    tags:
      - "v*"
  # just for manual testing
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up lowercase owner
        id: vars
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: mode=max
          cache-from: type=registry,ref=ghcr.io/${{ steps.vars.outputs.owner }}/${{ github.event.repository.name }}:latest
          cache-to: type=inline
          file: ./chef.debian.dockerfile
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
